packages:
  - frontend
  - frontend-app
  - frontend-app-demo
  - backend
  - shared

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - sharp
  - unrs-resolver
